### ISSUE TITLE
Where's the source?

### ISSUE THREAD

**Issue by computersforpeace** [andersson/tqftpserv#1]
Where am I supposed to get these from?

#include "list.h"
#include "servreg_loc.h"
#include "util.h"

**Comment by computersforpeace** [comment]
Oh, sorry, I see that list.h is here. servreg_loc.h seems unnecessary at the moment, and util.h just needs a trivial MAX() definition.

**Comment by andersson** [comment]
Thaks for the report, a fix was pushed some time ago. Sorry for leaving these the includes when pushing the original code.
